/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ItsButton {
    'label': string;
  }
  interface ItsInput {
    'label': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLItsButtonElement extends Components.ItsButton, HTMLStencilElement {}
  var HTMLItsButtonElement: {
    prototype: HTMLItsButtonElement;
    new (): HTMLItsButtonElement;
  };

  interface HTMLItsInputElement extends Components.ItsInput, HTMLStencilElement {}
  var HTMLItsInputElement: {
    prototype: HTMLItsInputElement;
    new (): HTMLItsInputElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'its-button': HTMLItsButtonElement;
    'its-input': HTMLItsInputElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface ItsButton {
    'label'?: string;
  }
  interface ItsInput {
    'label'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'its-button': ItsButton;
    'its-input': ItsInput;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'its-button': LocalJSX.ItsButton & JSXBase.HTMLAttributes<HTMLItsButtonElement>;
      'its-input': LocalJSX.ItsInput & JSXBase.HTMLAttributes<HTMLItsInputElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


